### ISSUE TITLE
Arty-A7 test producing unexpected results from master

### ISSUE THREAD

**Issue by tr-rocks** [antmicro/rowhammer-tester#110]
I have been running this tester on the arty-a7 board. When I started using it, when first following the instructions, the example command 

'python hw_rowhammer.py --nrows 512 --read_count 10e6 --pattern 01_in_row --row-pairs const --const-rows-pair 54 133 --no-refresh'

didn't initially produce any errors. I tried a previous commit of the tester from April 20th, and after using the exact same command the tester produced rowhammer errors as expected on rows 53, 55, 132, and 134. I experimented with the current version and found that using the 'const' attack with row numbers defined between 512-1024, 1536-2048, and higher rows between multiples of 512 and skipping multiples of 512 produces expected rowhammer errors (for example, using '--const-rows-pair 550 600' or '--const-rows-pair 1600 1700' both produce rowhammer errors)

Previous commit : a54dc46290c091591573f12bc989619eb76f1433

[Command1.txt](https://github.com/antmicro/litex-rowhammer-tester/files/8865339/command1.txt)
Output of command 1 from [current tester](https://github.com/antmicro/litex-rowhammer-tester/files/8865342/output1.txt)
Output of command 1 from [older commit](https://github.com/antmicro/litex-rowhammer-tester/files/8865343/output1_prev_commit.txt)

[Command2.txt](https://github.com/antmicro/litex-rowhammer-tester/files/8865340/command2.txt)
Output of command 2 from [current tester](https://github.com/antmicro/litex-rowhammer-tester/files/8865344/output2.txt)

**Comment by michalsieron** [comment]
I was able to reproduce reported behaviour. After quick `git bisect` I found commit at fault: https://github.com/antmicro/rowhammer-tester/commit/33286682a91dcd78e7d82b7c934f22134710d560

Luckily the issue was fixed in https://github.com/antmicro/rowhammer-tester/commit/51d6829e7fcb3090fc0234899cc9ab69e5bde2db

The thing that was happening, is that invalid pattern was being retrieved from `pattern_generator` which was 'all_0'.
On Arty board pattern 'all_0' doesn't produce bitflips (at least with 10e6 reads) on any commit I tested.

Now that correct pattern is used, you should be able to observe bitflips.
