### ISSUE TITLE
Hardware Memory Test Optimization and Batch Error Reporting

### ISSUE THREAD

**Issue by biecho** [antmicro/rowhammer-tester#184]
**Description**:
I have a couple of questions regarding potential optimizations in the way memory is checked against bitflips.

1. Is there a way in the hardware memory test module (which currently reports `BistError`s with offset, expected, etc.) to check only if an error occurred in a row, without the extra details?

2. Is it possible to implement a command that, given a list of row indices, can report whether an error occurred for each row (0 or 1) in one batch via EtherBridge?

**Additional Context**:

We would like to check for a list of rows as efficient as possible if an error occurred or not for each row. It would be awesome if this can be done within 50-100ms.

**Comment by tmichalak** [comment]
@biecho If I understand you correctly, you are looking for a procedure that scans the memory and checks if a bitflip occurred in a specific row. The Rowhammer platform doesn't support such a feature at the moment.
In order to achieve this functionality, the [Reader](https://github.com/antmicro/rowhammer-tester/blob/aa7ea8770bd0f3d2b4a59acc748d8a146ac84c61/rowhammer_tester/gateware/bist.py#L255) module would need to be modified. It would need a register to hold the row address, calculate the actual row address from the memory address sent over to the MC port. During data compare the Reader would need to check both data for bitflips and address for selected row and store the result in a register called detected_bitflips.

As for testing multiple rows in a single run, this could be built upon previous changes by replacing the row address register with a HW FIFO that would be populated with row indices through EtherBone. The result register would also have to be a HW FIFO.

Eventually, we would need to be able to switch between the full error description and row error mode and for that the existing result FIFO will need to be modified as well.
